apiVersion: apps/v1
kind: Deployment
metadata:
  name: federated-flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: federated-flask
  template:
    metadata:
      labels:
        app: federated-flask
    spec:
      containers:
        - name: federated-flask
          image: skyish/federated-flask:latest
          envFrom:
            - configMapRef:
                name: deployment-configmap
            - secretRef:
                name: deployment-secret
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: federated-flask-service
spec:
  type: ClusterIP
  selector:
    app: federated-flask
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
