apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2023-11-05T19:51:49Z"
  name: react-frontend-deployment
  namespace: food-flow
  resourceVersion: "511729"
  uid: 77d42f88-cdb4-476a-88a1-bd0bb61896ee
spec:
  maxReplicas: 8
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-frontend-deployment
