apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: skyish/react-frontend:latest
          resources:
            requests:
              memory: "2Gi"  
              cpu: "3"        
            limits:
              memory: "4Gi"   # Limit the federated learning
              cpu: "3"        
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
