apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-socket-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservation-socket
  template:
    metadata:
      labels:
        app: reservation-socket
    spec:
      containers:
        - name: reservation-socket
          image: skyish/reservation-socket:latest
          ports:
            - containerPort: 8282

---
apiVersion: v1
kind: Service
metadata:
  name: reservation-socket-service
spec:
  type: LoadBalancer
  selector:
    app: reservation-socket
  ports:
    - protocol: TCP
      port: 8282
      targetPort: 8282
