/**
 * @fileoverview gRPC-Web generated client stub for auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.15.8
// source: auth.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.auth = require('./auth_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.UsersServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.UsersServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.CreateUserDto,
 *   !proto.auth.ProtoUser>}
 */
const methodDescriptor_UsersService_CreateUser = new grpc.web.MethodDescriptor(
  '/auth.UsersService/CreateUser',
  grpc.web.MethodType.UNARY,
  proto.auth.CreateUserDto,
  proto.auth.ProtoUser,
  /**
   * @param {!proto.auth.CreateUserDto} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.ProtoUser.deserializeBinary
);


/**
 * @param {!proto.auth.CreateUserDto} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.ProtoUser)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.ProtoUser>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.UsersServiceClient.prototype.createUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.UsersService/CreateUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_CreateUser,
      callback);
};


/**
 * @param {!proto.auth.CreateUserDto} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.ProtoUser>}
 *     Promise that resolves to the response
 */
proto.auth.UsersServicePromiseClient.prototype.createUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.UsersService/CreateUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_CreateUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.Empty,
 *   !proto.auth.Users>}
 */
const methodDescriptor_UsersService_FindAllUsers = new grpc.web.MethodDescriptor(
  '/auth.UsersService/FindAllUsers',
  grpc.web.MethodType.UNARY,
  proto.auth.Empty,
  proto.auth.Users,
  /**
   * @param {!proto.auth.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.Users.deserializeBinary
);


/**
 * @param {!proto.auth.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.Users)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.Users>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.UsersServiceClient.prototype.findAllUsers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.UsersService/FindAllUsers',
      request,
      metadata || {},
      methodDescriptor_UsersService_FindAllUsers,
      callback);
};


/**
 * @param {!proto.auth.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.Users>}
 *     Promise that resolves to the response
 */
proto.auth.UsersServicePromiseClient.prototype.findAllUsers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.UsersService/FindAllUsers',
      request,
      metadata || {},
      methodDescriptor_UsersService_FindAllUsers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.FindOneUserDto,
 *   !proto.auth.ProtoUser>}
 */
const methodDescriptor_UsersService_FindOneUser = new grpc.web.MethodDescriptor(
  '/auth.UsersService/FindOneUser',
  grpc.web.MethodType.UNARY,
  proto.auth.FindOneUserDto,
  proto.auth.ProtoUser,
  /**
   * @param {!proto.auth.FindOneUserDto} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.ProtoUser.deserializeBinary
);


/**
 * @param {!proto.auth.FindOneUserDto} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.ProtoUser)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.ProtoUser>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.UsersServiceClient.prototype.findOneUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.UsersService/FindOneUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_FindOneUser,
      callback);
};


/**
 * @param {!proto.auth.FindOneUserDto} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.ProtoUser>}
 *     Promise that resolves to the response
 */
proto.auth.UsersServicePromiseClient.prototype.findOneUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.UsersService/FindOneUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_FindOneUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.UpdateUserDto,
 *   !proto.auth.ProtoUser>}
 */
const methodDescriptor_UsersService_UpdateUser = new grpc.web.MethodDescriptor(
  '/auth.UsersService/UpdateUser',
  grpc.web.MethodType.UNARY,
  proto.auth.UpdateUserDto,
  proto.auth.ProtoUser,
  /**
   * @param {!proto.auth.UpdateUserDto} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.ProtoUser.deserializeBinary
);


/**
 * @param {!proto.auth.UpdateUserDto} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.ProtoUser)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.ProtoUser>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.UsersServiceClient.prototype.updateUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.UsersService/UpdateUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_UpdateUser,
      callback);
};


/**
 * @param {!proto.auth.UpdateUserDto} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.ProtoUser>}
 *     Promise that resolves to the response
 */
proto.auth.UsersServicePromiseClient.prototype.updateUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.UsersService/UpdateUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_UpdateUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.FindOneUserDto,
 *   !proto.auth.ProtoUser>}
 */
const methodDescriptor_UsersService_RemoveUser = new grpc.web.MethodDescriptor(
  '/auth.UsersService/RemoveUser',
  grpc.web.MethodType.UNARY,
  proto.auth.FindOneUserDto,
  proto.auth.ProtoUser,
  /**
   * @param {!proto.auth.FindOneUserDto} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.ProtoUser.deserializeBinary
);


/**
 * @param {!proto.auth.FindOneUserDto} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.ProtoUser)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.ProtoUser>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.UsersServiceClient.prototype.removeUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.UsersService/RemoveUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_RemoveUser,
      callback);
};


/**
 * @param {!proto.auth.FindOneUserDto} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.ProtoUser>}
 *     Promise that resolves to the response
 */
proto.auth.UsersServicePromiseClient.prototype.removeUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.UsersService/RemoveUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_RemoveUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.LoginRequest,
 *   !proto.auth.LoginResponse>}
 */
const methodDescriptor_UsersService_Login = new grpc.web.MethodDescriptor(
  '/auth.UsersService/Login',
  grpc.web.MethodType.UNARY,
  proto.auth.LoginRequest,
  proto.auth.LoginResponse,
  /**
   * @param {!proto.auth.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.auth.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.UsersServiceClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.UsersService/Login',
      request,
      metadata || {},
      methodDescriptor_UsersService_Login,
      callback);
};


/**
 * @param {!proto.auth.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.auth.UsersServicePromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.UsersService/Login',
      request,
      metadata || {},
      methodDescriptor_UsersService_Login);
};


module.exports = proto.auth;

