---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1
  labels:
    app: kafka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-1:22181,zookeeper-2:32181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,OUTSIDE://localhost:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-2
  labels:
    app: kafka-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 39092
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-1:22181,zookeeper-2:32181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,OUTSIDE://localhost:39092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"


---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service-1 
spec:
  selector:
    app: kafka-1
  ports:
    - name: kafka
      protocol: TCP
      port: 29092
      targetPort: 29092

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service-2 
spec:
  selector:
    app: kafka-2
  ports:
    - name: kafka
      protocol: TCP
      port: 39092
      targetPort: 39092

