apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-reservation-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-reservation
  template:
    metadata:
      labels:
        app: react-reservation
    spec:
      containers:
        - name: react-reservation
          image: skyish/react-reservation:latest
          ports:
            - containerPort: 5003

---

apiVersion: v1
kind: Service
metadata:
  name: react-reservation-service
spec:
  selector:
    app: react-reservation
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003 
