apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-envoy-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-envoy-service
            port:
              number: 9900
