apiVersion: v1
kind: Secret
metadata:
  name: mysecrets
data:
  AWS_SECRET_ACCESS_KEY: Z1BpVitUZU9pSXVvT3EwbXJxQnFVaVVQY1ZXRlA0clpVQ2VEeDZDVQ==
  SECRET_KEY_2: c2VjcmV0X2tleV8y
  SECRET_KEY_3: c2VjcmV0X2tleV8z
