---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment-1
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper-container
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment-2
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper-container
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-1
spec:
  selector:
    app: zookeeper
  ports:
    - name: client
      protocol: TCP
      port: 22181
      targetPort: 2181

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-2
spec:
  selector:
    app: zookeeper
  ports:
    - name: client
      protocol: TCP
      port: 32181
      targetPort: 2181
