apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: skyish/food-flow:reservation
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  selector:
    app: reservation
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 